# Generated by Django 6.0.1 on 2026-01-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("file", models.FileField(upload_to="datasets/")),
                ("total_count", models.IntegerField(default=0)),
                ("avg_flowrate", models.FloatField(blank=True, null=True)),
                ("avg_pressure", models.FloatField(blank=True, null=True)),
                ("avg_temperature", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
